name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 7.1
          - 7.2
          - 7.3
          - 7.4

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - uses: "ramsey/composer-install@v1"

      - name: Code style check
        run: vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --verbose
      - name: Unit tests
        run: vendor/bin/atoum
